/// Flutter icons CaptainProfileIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CaptainProfileIcons
///      fonts:
///       - asset: fonts/CaptainProfileIcons.ttf
///
/// 
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
///
import 'package:flutter/widgets.dart';

class CaptainProfileIcons {
  CaptainProfileIcons._();

  static const _kFontFam = 'CaptainProfileIcons';
  static const String? _kFontPkg = null;

  static const IconData chat = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lang = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData payment = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walet = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData analyze = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clients_help = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
